/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrincipalsIndexRouteImport } from './routes/principals/index'
import { Route as RegistrationsIndexRouteImport } from './routes/registrations/index'
import { Route as RegistrationsRegistrationIdRouteImport } from './routes/registrations/$registrationId'
import { Route as WorkloadsIndexRouteImport } from './routes/workloads/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalsIndexRoute = PrincipalsIndexRouteImport.update({
  id: '/principals/',
  path: '/principals/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsIndexRoute = RegistrationsIndexRouteImport.update({
  id: '/registrations/',
  path: '/registrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRegistrationIdRoute =
  RegistrationsRegistrationIdRouteImport.update({
    id: '/registrations/$registrationId',
    path: '/registrations/$registrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkloadsIndexRoute = WorkloadsIndexRouteImport.update({
  id: '/workloads/',
  path: '/workloads/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registrations/$registrationId': typeof RegistrationsRegistrationIdRoute
  '/principals/': typeof PrincipalsIndexRoute
  '/registrations/': typeof RegistrationsIndexRoute
  '/workloads/': typeof WorkloadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registrations/$registrationId': typeof RegistrationsRegistrationIdRoute
  '/principals': typeof PrincipalsIndexRoute
  '/registrations': typeof RegistrationsIndexRoute
  '/workloads': typeof WorkloadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registrations/$registrationId': typeof RegistrationsRegistrationIdRoute
  '/principals/': typeof PrincipalsIndexRoute
  '/registrations/': typeof RegistrationsIndexRoute
  '/workloads/': typeof WorkloadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registrations/$registrationId'
    | '/principals/'
    | '/registrations/'
    | '/workloads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registrations/$registrationId'
    | '/principals'
    | '/registrations'
    | '/workloads'
  id:
    | '__root__'
    | '/'
    | '/registrations/$registrationId'
    | '/principals/'
    | '/registrations/'
    | '/workloads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistrationsRegistrationIdRoute: typeof RegistrationsRegistrationIdRoute
  PrincipalsIndexRoute: typeof PrincipalsIndexRoute
  RegistrationsIndexRoute: typeof RegistrationsIndexRoute
  WorkloadsIndexRoute: typeof WorkloadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principals/': {
      id: '/principals/'
      path: '/principals'
      fullPath: '/principals/'
      preLoaderRoute: typeof PrincipalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations/': {
      id: '/registrations/'
      path: '/registrations'
      fullPath: '/registrations/'
      preLoaderRoute: typeof RegistrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations/$registrationId': {
      id: '/registrations/$registrationId'
      path: '/registrations/$registrationId'
      fullPath: '/registrations/$registrationId'
      preLoaderRoute: typeof RegistrationsRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workloads/': {
      id: '/workloads/'
      path: '/workloads'
      fullPath: '/workloads/'
      preLoaderRoute: typeof WorkloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistrationsRegistrationIdRoute: RegistrationsRegistrationIdRoute,
  PrincipalsIndexRoute: PrincipalsIndexRoute,
  RegistrationsIndexRoute: RegistrationsIndexRoute,
  WorkloadsIndexRoute: WorkloadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
